### ISSUE TITLE
Beware of NETGUARD.IO/jusdepomme

### ISSUE THREAD

**Issue by ghost** [Charterino/AsStrongAsFuck#4]
Beware of NETGUARD.IO/jusdepomme
He logs your files and looks through the code, not only that but he bribes his customers.
He asks users to leave good reviews in return of him giving them free points.
Here is the review and customer - ![](https://outbuilt.ooo/o/r2.png)
Here is jusde giving the point for that review - ![](https://outbuilt.ooo/o/db.png)
Besides from that he is looking through his customers - ![](https://outbuilt.ooo/o/1l.png)
He sent screenshots of my code from Outbuilt.dll that I protected using his protection and trying to say that its skidded.
He sees that I unpacked his shit and he banned me from his service when I already was banned - ![](https://outbuilt.ooo/o/uy.png)
He also logs IP's and threaten to take me to court - ![](https://outbuilt.ooo/o/dh.png) | ![](https://outbuilt.ooo/o/8g.png)
He's 100% a scum, don't use his services.

**Comment by Charterino** [comment]
Woah. Im not sure how is that related to ASAF. Logging IPs and giving free points for reviews is common thing.
