### ISSUE TITLE
Add Protections

### ISSUE THREAD

**Issue by wvay** [Charterino/AsStrongAsFuck#5]
Add some additionals methods such as Virtualization or someshit else

**Comment by Moooog** [comment]
why dont you

**Comment by wvay** [comment]
@Moooog why is this repository opened? cause the developer wants to improve his code knowledge right? so please shut up, a virtualization is the best method to learn how opcodes works.

**Comment by b1sergiu** [comment]
What is the point of opening this issue? Fork it, add it yourself and open a pull request lmao

**Comment by wvay** [comment]
@b1sergiu i'm not usual to use github, so i don't know how it works perfectly
